# BlockCmdPerVer configuration

# Version of the config to allow for config migration. Do not change this
# If you accidentally delete/change it, you can regenerate it by removing the option and restarting the server
version: 2

# Whether the plugin is enabled. Set this to false to disable the plugin
# Default: true
enabled: true

# Whether to allow bypassing the check with the permission bcpver.bypass
# Default: false
bypass-permission: false

# Blocked commands per version. Put the commands you want to block per version in the version's brackets.
# Example: If you want to block the /summon and /give commands on 1.7, change the 1.7 line to this (quotes not required):
# 1.7: ["summon", "give"]
# This can also be done by putting new lines after the version name with a dash and then the command. Ex:
# 1.7:
# - summon
# - give
# The versions include all minor versions (Ex: the 1.12 option also includes 1.12.1 and 1.12.2)
versions: {}