name: BlockCmdPerVer
author: BuzzTheGamer23
version: 1.1.0
main: com.buzzthegamer23.blockcmdperver.BlockCmdPerVer
description: Allows you to block specific commands per Minecraft version
api-version: 1.13
softdepends: [ViaVersion, ProtocolSupport]