name: BlockCmdPerVer
author: buzzcoding
version: 2.0.0
main: io.github.buzzcoding.blockcmdperver.BlockCmdPerVer
description: Allows you to block specific commands per Minecraft version
api-version: 1.13
softdepend: [ViaVersion, ProtocolSupport]
permissions:
  bcpver.bypass:
    description: Permission to bypass the command block. Can be enabled/disabled from the config
    default: false